### ISSUE TITLE
getting http 410 errors on connection

### ISSUE THREAD

**Issue by bcohen44** [prant0-ssp/autodoist#1]
Running python3.10, `Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux`

Getting 410 errors + logging tracebacks, 

```
bcohen@laptop-bcohen02:~/scripts/autodoist$ python3 autodoist.py -a <xyz> -l next_action --debug
2023-08-16 06:04:26 DEBUG    Starting new HTTPS connection (1): api.github.com:443
2023-08-16 06:04:26 DEBUG    https://api.github.com:443 "GET /repos/Hoffelhas/autodoist/releases HTTP/1.1" 200 None
2023-08-16 06:04:26 WARNING  

Your version is not up-to-date! 
Your version: v1.5. Latest version: v2.0
Find the latest version at: https://github.com/Hoffelhas/autodoist/releases/tag/v2.0

2023-08-16 06:04:26 INFO     You are running with the following functionalities:

   Next action labelling mode: Enabled
   Regenerate sub-tasks mode: Disabled
   Shifted end-of-day mode: Disabled

2023-08-16 06:04:26 DEBUG    Connecting to the Todoist API
2023-08-16 06:04:26 DEBUG    Syncing the current state from the API
2023-08-16 06:04:26 DEBUG    Starting new HTTPS connection (1): api.todoist.com:443
2023-08-16 06:04:27 DEBUG    https://api.todoist.com:443 "POST /sync/v8/sync HTTP/1.1" 410 None
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: %d format: a real number is required, not str
Call stack:
  File "/home/BOSDYN/bcohen/scripts/autodoist/autodoist.py", line 1005, in <module>
    main()
  File "/home/BOSDYN/bcohen/scripts/autodoist/autodoist.py", line 959, in main
    api, label_id, regen_labels_id = initialise(args)
  File "/home/BOSDYN/bcohen/scripts/autodoist/autodoist.py", line 166, in initialise
    label_id = verify_label_existance(args, api, args.label, 1)
  File "/home/BOSDYN/bcohen/scripts/autodoist/autodoist.py", line 83, in verify_label_existance
    logging.debug('Label \'%s\' found as label id %d',
Message: "Label '%s' found as label id %d"
Arguments: ('next_action', 'bf16b708-3b6c-11ee-b7ae-cd769a7403e9')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: %d format: a real number is required, not str
Call stack:
  File "/home/BOSDYN/bcohen/scripts/autodoist/autodoist.py", line 1005, in <module>
    main()
  File "/home/BOSDYN/bcohen/scripts/autodoist/autodoist.py", line 959, in main
    api, label_id, regen_labels_id = initialise(args)
  File "/home/BOSDYN/bcohen/scripts/autodoist/autodoist.py", line 166, in initialise
    label_id = verify_label_existance(args, api, args.label, 1)
  File "/home/BOSDYN/bcohen/scripts/autodoist/autodoist.py", line 83, in verify_label_existance
    logging.debug('Label \'%s\' found as label id %d',
Message: "Label '%s' found as label id %d"
Arguments: ('next_action', 'bf16b708-3b6c-11ee-b7ae-cd769a7403e9')
2023-08-16 06:04:27 INFO     Autodoist has connected and is running fine!

2023-08-16 06:04:27 DEBUG    Syncing the current state from the API
2023-08-16 06:04:27 DEBUG    https://api.todoist.com:443 "POST /sync/v8/sync HTTP/1.1" 410 None
2023-08-16 06:04:27 INFO     No changes in queue, skipping sync.
2023-08-16 06:04:27 DEBUG    Sleeping for 4 seconds
```

**Comment by bcohen44** [comment]
Nevermind, this was running 1.5 instead of 2.0
